version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Core data science and framework dependencies
      core-dependencies:
        patterns:
          - "pandas*"
          - "numpy*"
          - "matplotlib*"
          - "pydantic*"
        update-types:
          - "patch"
          - "minor"
      # Web API and server dependencies
      web-dependencies:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "aiohttp*"
          - "starlette*"
          - "anyio*"
        update-types:
          - "patch"
          - "minor"
      # Development and testing tools
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black*"
          - "isort*"
          - "mypy*"
          - "flake8*"
          - "ruff*"
          - "pre-commit*"
          - "coverage*"
        update-types:
          - "patch"
          - "minor"
      # Security updates (grouped for efficiency)
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all GitHub Actions updates
      github-actions-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      # Security updates for actions
      github-actions-security:
        patterns:
          - "*"
        update-types:
          - "security-update"

  # Node.js dependencies (for frontend/docs)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Core Next.js and React dependencies
      frontend-core:
        patterns:
          - "next*"
          - "react*"
          - "@types/react*"
        update-types:
          - "patch"
          - "minor"
      # Development dependencies
      frontend-dev:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript*"
          - "tailwindcss*"
          - "postcss*"
          - "autoprefixer*"
        update-types:
          - "patch"
          - "minor"
      # UI and charting libraries
      frontend-ui:
        patterns:
          - "recharts*"
          - "lucide-react*"
        update-types:
          - "patch"
          - "minor"
      # Security updates for npm packages
      frontend-security:
        patterns:
          - "*"
        update-types:
          - "security-update"