version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      core-dependencies:
        patterns:
          - "pandas*"
          - "numpy*"
          - "matplotlib*"
          - "pydantic*"
      web-dependencies:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "aiohttp*"
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black*"
          - "isort*"
          - "mypy*"
          - "flake8*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Node.js dependencies (for frontend/docs)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
      include: "scope"