[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fantastic-palm-tree"
version = "0.2.0"
description = "Advanced backtesting framework with ATR-based exits, risk controls, and extensible strategy components"
readme = "README.md"
authors = [{ name = "Xivlon" }]
license = { text = "MIT" }
requires-python = ">=3.10"
keywords = ["trading", "backtest", "strategy", "risk", "ATR"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Developers",
  "Intended Audience :: Financial and Insurance Industry",
  "Topic :: Office/Business :: Financial :: Investment"
]
dependencies = []

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "pytest-cov>=5.0",
  "mypy>=1.8",
  "ruff>=0.5.0",
  "rich>=13.0"
]

[tool.pytest.ini_options]
addopts = "-ra"
python_files = ["test_*.py", "*_test.py"]

[tool.coverage.run]
branch = true
source = ["."]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
strict = true
ignore_missing_imports = true

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "B", "UP", "ANN", "N"]
ignore = ["ANN101", "ANN102"]

[tool.ruff.format]
quote-style = "double"