[project]
name = "fantastic-palm-tree"
version = "0.1.0"
description = ""
authors = []

[tool.setuptools]
packages = ["fantastic_palm_tree"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"