blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Report
    url: https://github.com/Xivlon/fantastic-palm-tree/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories
  - name: Discussion Forum
    url: https://github.com/Xivlon/fantastic-palm-tree/discussions
    about: Ask questions and discuss ideas with the community